### ISSUE TITLE
0.15.10: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/createrepo_c#217]
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test ARGS=-V
Running tests...
/usr/bin/ctest --force-new-ctest-process -V
UpdateCTestConfiguration  from :/home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/DartConfiguration.tcl
Test project /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: test_main

1: Test command: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/run_gtester.sh
1: Test timeout computed to be: 10000000
1: Number of fails: 0
1/2 Test #1: test_main ........................   Passed    0.01 sec
test 2
    Start 2: test_python

2: Test command: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/python/tests/run_nosetests.sh "-s" "/home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/python/tests"
2: Test timeout computed to be: 10000000
2: test_checksum_name_str (tests.test_checksum.TestCaseChecksum) ... ok
2: test_checksum_type (tests.test_checksum.TestCaseChecksum) ... ok
2: test_compression_suffix (tests.test_compression_wrapper.TestCaseCompressionWrapper) ... ok
2: test_compression_type (tests.test_compression_wrapper.TestCaseCompressionWrapper) ... ok
2: test_detect_compression (tests.test_compression_wrapper.TestCaseCompressionWrapper) ... ok
2: test_contentstat (tests.test_contentstat.TestCaseContentStat) ... ok
2: Test if reference is saved properly ... ok
2: Test if reference is saved properly ... ok
2: test_crfile_basic_operations (tests.test_crfile.TestCaseCrFile) ... ok
2: test_crfile_bz2_compression (tests.test_crfile.TestCaseCrFile) ... ok
2: test_crfile_error_cases (tests.test_crfile.TestCaseCrFile) ... ok
2: test_crfile_gz_compression (tests.test_crfile.TestCaseCrFile) ... ok
2: test_crfile_no_compression (tests.test_crfile.TestCaseCrFile) ... ok
2: test_crfile_operations_on_closed_file (tests.test_crfile.TestCaseCrFile) ... ok
2: test_crfile_xz_compression (tests.test_crfile.TestCaseCrFile) ... ERROR
2: test_crfile_zck_compression (tests.test_crfile.TestCaseCrFile) ... ok
2: test_load_metadata_repo00 (tests.test_load_metadata.TestCaseLoadMetadata) ... ok
2: test_load_metadata_repo01 (tests.test_load_metadata.TestCaseLoadMetadata) ... ok
2: test_load_metadata_repo02 (tests.test_load_metadata.TestCaseLoadMetadata) ... ok
2: test_load_metadata_repo02_destructor (tests.test_load_metadata.TestCaseLoadMetadata) ... ok
2: test_metadatalocation (tests.test_locate_metadata.TestCaseMetadataLocation) ... C_CREATEREPOLIB-Message: 19:05:32.237: type group added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/04460bfaf6cb5af6b0925d8c99401a44e5192d287796aed4cced5f7ce881761f-comps.f20.xml
2: C_CREATEREPOLIB-Message: 19:05:32.237: type group_gz added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/f9d860ddcb64fbdc88a9b71a14ddb9f5670968d5dd3430412565c13d42b6804d-comps.f20.xml.gz
2: C_CREATEREPOLIB-Message: 19:05:32.237: type group_gz_zck added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/2bbdf70c4394e71c2d3905c143d460009d04359de5a90b72b47cdb9dbdcc079d-comps.f20.xml.gz.zck
2: C_CREATEREPOLIB-Message: 19:05:32.238: type group_zck added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/2bbdf70c4394e71c2d3905c143d460009d04359de5a90b72b47cdb9dbdcc079d-comps.f20.xml.zck
2: C_CREATEREPOLIB-Message: 19:05:32.238: type modules added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/4fbad65c641f4f8fb3cec9b1672fcec2357443e1ea6e93541a0bb559c7dc9238-modules.yaml.gz
2: C_CREATEREPOLIB-Message: 19:05:32.238: type modules_zck added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/cb0f4b5df8268f248158e50d66ee1565591bca23ee2dbd84ae9c457962fa3122-modules.yaml.gz.zck
2: C_CREATEREPOLIB-Message: 19:05:32.238: type updateinfo added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/88514679cb03d8f51e850ad3639c089f899e83407a2380ef9e62873a8eb1db13-updateinfo_01.xml.gz
2: C_CREATEREPOLIB-Message: 19:05:32.238: type updateinfo_zck added to list from path: /home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/testdata/repo_with_additional_metadata/repodata/0219a2f1f9f32af6b7873905269ac1bc27b03e0caf3968c929a49e5a939e8935-updateinfo_01.xml.gz.zck
2: ok
2: test_compress_file (tests.test_misc.TestCaseMisc) ... ok
2: test_decompress_file (tests.test_misc.TestCaseMisc) ... ok
2: test_package_archer (tests.test_package.TestCasePackage) ... ok
2: test_package_copying (tests.test_package.TestCasePackage) ... ok
2: test_package_empty (tests.test_package.TestCasePackage) ... ok
2: test_package_setters (tests.test_package.TestCasePackage) ... ok
2: test_package_from_rpm (tests.test_parsepkg.TestCaseParsepkg) ...
2: (process:2148075): C_CREATEREPOLIB-WARNING **: 19:05:32.254: read_header: Fopen of this_foo_pkg_shoud_not_exists.rpm failed No such file or directory
2: error: ./: read failed: Is a directory (21)
2:
2:
2: (process:2148075): C_CREATEREPOLIB-WARNING **: 19:05:32.254: read_header: rpmReadPackageFile() error
2:
2: (process:2148075): C_CREATEREPOLIB-WARNING **: 19:05:32.254: read_header: rpmReadPackageFile() error
2: ok
2: test_xml_from_rpm (tests.test_parsepkg.TestCaseParsepkg) ...
2: (process:2148075): C_CREATEREPOLIB-WARNING **: 19:05:32.255: read_header: Fopen of this_foo_pkg_shoud_not_exists.rpm failed No such file or directory
2: error: ./: read failed: Is a directory (21)
2:
2:
2: (process:2148075): C_CREATEREPOLIB-WARNING **: 19:05:32.255: read_header: rpmReadPackageFile() error
2:
2: (process:2148075): C_CREATEREPOLIB-WARNING **: 19:05:32.255: read_header: rpmReadPackageFile() error
2: ok
2: test_repomd (tests.test_repomd.TestCaseRepomd) ... ok
2: test_repomd_indexing_and_iteration_repo01 (tests.test_repomd.TestCaseRepomd) ... ok
2: test_repomd_with_path_in_constructor_repo01 (tests.test_repomd.TestCaseRepomd) ... ok
2: test_repomdrecord_compress_and_fill (tests.test_repomdrecord.TestCaseRepomdRecord) ... ok
2: test_repomdrecord_fill (tests.test_repomdrecord.TestCaseRepomdRecord) ... ok
2: test_repomdrecord_load_contentstat (tests.test_repomdrecord.TestCaseRepomdRecord) ... ok
2: test_repomdrecord_setters (tests.test_repomdrecord.TestCaseRepomdRecord) ... ok
2: test_sqlite_basic_operations (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_error_cases (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_filelists (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_filelists_schema (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_operations_on_closed_db (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_other (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_other_schema (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_primary (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_sqlite_primary_schema (tests.test_sqlite.TestCaseSqlite) ... ok
2: test_updatecollection_setters (tests.test_updatecollection.TestCaseUpdateCollection) ... ok
2: test_updatecollection_setters_when_module_going_out_of_scope (tests.test_updatecollection.TestCaseUpdateCollection) ... ok
2: test_updatecollectionmodule_setters (tests.test_updatecollectionmodule.TestCaseUpdateCollectionModule) ... ok
2: test_updatecollectionpackage_setters (tests.test_updatecollectionpackage.TestCaseUpdateCollectionPackage) ... ok
2: test_updateinfo_setters (tests.test_updateinfo.TestCaseUpdateInfo) ... ok
2: test_updateinfo_xml_dump_01 (tests.test_updateinfo.TestCaseUpdateInfo) ... ok
2: test_updateinfo_xml_dump_02 (tests.test_updateinfo.TestCaseUpdateInfo) ... ok
2: test_updateinfo_xml_dump_03 (tests.test_updateinfo.TestCaseUpdateInfo) ... ok
2: test_updateinfo_xml_dump_04 (tests.test_updateinfo.TestCaseUpdateInfo) ... ok
2: test_updateinfo_xml_dump_05 (tests.test_updateinfo.TestCaseUpdateInfo) ... ok
2: test_updaterecord_setters (tests.test_updaterecord.TestCaseUpdateRecord) ... ok
2: test_xml_dump_updaterecord (tests.test_updaterecord.TestCaseUpdateRecord) ... ok
2: test_updatereference_setters (tests.test_updatereference.TestCaseUpdateReference) ... ok
2: test_version (tests.test_version.TestCaseVersion) ... ok
2: test_xmlfile_add_chunk (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_add_pkg (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_basic_operations (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_bz2_compression (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_error_cases (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_gz_compression (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_no_compression (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_operations_on_closed_file (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_set_num_of_pkgs (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xmlfile_xz_compression (tests.test_xml_file.TestCaseXmlFile) ... ERROR
2: test_xmlfile_zck_compression (tests.test_xml_file.TestCaseXmlFile) ... ok
2: test_xml_parser_filelists_error (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_newpkgcb_abort (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_pkgcb_abort (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_repo01 (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_repo02 (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_repo02_no_cbs (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_repo02_only_pkgcb (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_snippet01 (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_snippet02 (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_warningcb_abort (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_filelists_warnings (tests.test_xml_parser.TestCaseXmlParserFilelists) ... ok
2: test_xml_parser_other_error (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_newpkgcb_abort (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_pkgcb_abort (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_repo01 (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_repo02 (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_repo02_no_cbs (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_repo02_only_pkgcb (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_snippet01 (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_snippet02 (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_warningcb_abort (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_other_warnings (tests.test_xml_parser.TestCaseXmlParserOther) ... ok
2: test_xml_parser_primary_error (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_newpkgcb_abort (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_pkgcb_abort (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_repo01 (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_repo02 (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_repo02_no_cbs (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_repo02_only_pkgcb (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_snippet01 (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_snippet02 (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_warningcb_abort (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_primary_warnings (tests.test_xml_parser.TestCaseXmlParserPrimary) ... ok
2: test_xml_parser_repomd_bad_repomd_object (tests.test_xml_parser.TestCaseXmlParserRepomd) ... ok
2: test_xml_parser_repomd_repo01 (tests.test_xml_parser.TestCaseXmlParserRepomd) ... ok
2: test_xml_parser_repomd_repo01_nowarningcb (tests.test_xml_parser.TestCaseXmlParserRepomd) ... ok
2:
2: ======================================================================
2: ERROR: test_crfile_xz_compression (tests.test_crfile.TestCaseCrFile)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/python/tests/test_crfile.py", line 104, in test_crfile_xz_compression
2:     p = subprocess.Popen(["unxz", "--stdout", path], stdout=subprocess.PIPE)
2:   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
2:     self._execute_child(args, executable, preexec_fn, close_fds,
2:   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
2:     raise child_exception_type(errno_num, err_msg, err_filename)
2: FileNotFoundError: [Errno 2] No such file or directory: 'unxz'
2:
2: ======================================================================
2: ERROR: test_xmlfile_xz_compression (tests.test_xml_file.TestCaseXmlFile)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/home/tkloczko/rpmbuild/BUILD/createrepo_c-0.15.10/tests/python/tests/test_xml_file.py", line 131, in test_xmlfile_xz_compression
2:     p = subprocess.Popen(["unxz", "--stdout", path], stdout=subprocess.PIPE)
2:   File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
2:     self._execute_child(args, executable, preexec_fn, close_fds,
2:   File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
2:     raise child_exception_type(errno_num, err_msg, err_filename)
2: FileNotFoundError: [Errno 2] No such file or directory: 'unxz'
2:
2: ----------------------------------------------------------------------
2: Ran 106 tests in 0.131s
2:
2: FAILED (errors=2)
2/2 Test #2: test_python ......................***Failed    0.63 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.65 sec

The following tests FAILED:
          2 - test_python (Failed)
Errors while running CTest
make: *** [Makefile:153: test] Error 8
```
Source code confiruration options:
`+ /usr/bin/cmake -DBUILD_SHARED_LIBS=ON  -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr  -DCMAKE_VERBOSE_MAKEFILE=ON -DINCLUDE_INSTALL_DIR=/usr/include -DLIB_INSTALL_DIR=/usr/lib64 -DLIB_SUFFIX=64 -DSHARE_INSTALL_PREFIX=/usr/share -DSYSCONF_INSTALL_DIR=/etc . -DENABLE_DRPM=OFF -DPYTHON_DESIRED:FILEPATH=/usr/bin/python3 -DWITH_LIBMODULEMD=OFF -DWITH_ZCHUNK=ON`

**Comment by kontura** [comment]
You are missing the xz dependency, specifically the binaries it provides (`unxz` decompresses .xz files)

This is certainly not specific to this new version of createrepo_c.

**Comment by kloczek** [comment]
Yep that was missing symlink after fs crash.

Thx. Closing.
